spring.application.name=Splitwise

spring.datasource.url=jdbc:postgresql://localhost:5432/split_wise
spring.datasource.username=abhishekyadav
spring.datasource.password=

# Additional property for Hibernate (JPA) specific settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true